version: '2'
services:
  collmate-app:
    image: collmate
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://collmate-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Collmate
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  collmate-mongodb:
    extends:
      file: mongodb.yml
      service: collmate-mongodb
